FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# TeambitionAPI

Teambition API 文档

## 群组 [/api/groups]

### 创建群组 [POST]

+ Request (application/json)

        {
            "name": "X",
            "userIds": [
                "582ac0358a40417b939859e8"
            ],
            "_organizationId": "582ac0358a40417b939859e4"
        }

+ Response 200 (application/json)

        {
            "_id": "582acba5d530e4bc956b5054",
            "name": "X",
            "_organizationId": "582acba5d530e4bc956b5033",
            "_creatorId": "5109f1e918e6fcfc560001a6",
            "hasMembers": [
                {
                "_id": "582acba5d530e4bc956b5037",
                "avatarUrl": "",
                "name": "name2",
                "pinyin": "name2",
                "py": "name2",
                "isDefaultEmail": false
                },
                {
                "_id": "5109f1e918e6fcfc560001a6",
                "avatarUrl": "http://www.teambition.com/site_media/user_avatars/20120928112820_349.png",
                "name": "测试账号",
                "pinyin": "ce shi zhang hao",
                "py": "cszh",
                "isDefaultEmail": false
                }
            ],
            "created": "2016-11-15T08:47:33.567Z",
            "updated": "2016-11-15T08:47:33.567Z",
            "pinyin": "x",
            "py": "x"
        }